version: "2.0"

services:
  scrapper:
    build: ./scrapper
    volumes:
      - ./scrapper:/scrapper
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    build: ./phpmyadmin
    ports:
      - 4000:80
    links:
      - mysql:db